export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const START_DIALOG = 'START_DIALOG';
export const NEXT_DIALOG = 'NEXT_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const ADD_TASK = 'ADD_TASK';
export const CHANGE_STATUS_TASK = 'CHANGE_STATUS_TASK';
export const ADD_TIP_TO_TASK = 'ADD_TIP_TO_TASK';
export const SAVE_CHARACTER_TO_HISTORY = 'SAVE_CHARACTER_TO_HISTORY';
